### PR TITLE
Add/remove friend functionality

### PR DESCRIPTION
**Pull request by chrishill93**
Added friend_management.py to allow for adding and removing friend functionality.  Also added a test file.  As I had some issues trying to integrate our own database into the database_setup test file, I went for an In-memory SQLite test database.  This creates a database in RAM for the duration of the test session, and should work to test the functionality of friend_management.py without relying on app.py (allowing for lower coupling).

### CODE REVIEW

**Comment by chrishill93** [comment]
Pretty sure I opened a new branch for block user, but didn't expect it to affect this pull request.  Will just push forward anyway, but this pull request will now include both the Add/Remove Friend Functionality issue, and the Block User Functionality issue.

**Comment by chrishill93** [comment]
I figured out the branching error I made.  I forgot to switch my repository in VSCode before making changes and pushing.

**Review by Sawneet-24 — APPROVED** [review]
Everything looks great. Tests have passed

**Comment by Graves067** [comment]
Awesome! Code looks good cant wait to start integrating this with our webpages!

**Review by Graves067 — APPROVED** [review]

**Pull request merged**
