### PR TITLE
Login Functionality Added

### PR DESCRIPTION
**Pull request by chrishill93**
Added a very basic login functionality in the form of login.py
Added routes.py to go along with it (this will direct traffic to URL endpoints)
Added __init__.py (this will allow Python to recognize the flask folder as a package)
Renamed main.py to app.py
Added test_login.py

### CODE REVIEW

**Comment by jacobtizel** [comment]
You should merge login.py with the app.py file

**Comment by chrishill93** [comment]
Hot damn that is satisfying

**Comment by jacobtizel** [comment]
Let it be known that for functional purposes all the flask files have been moved to the project folder. The flask installation is still in the project folder, which should be fine. The requirements.txt file is now in the project folder, though.

**Review by Graves067 — APPROVED** [review]
Looks solid!

**Pull request merged**
